### ISSUE TITLE
Clear좆같은 버그

### ISSUE THREAD

**Issue by yenapple** [Big-BlueBerry/GCS#2]
도형을 생성시에 Clear 버튼 위에서 마우스를 떼면 도형이 겉으로 보기엔 없어지면서(사실은 객체 삭제가 안됨) 그 다음부터 생성되는 도형들의 위치가 바뀜(특히 점의 경우, 없어졌던 것 같은 도형이 있던 위치 위에 찍힘 )

**Comment by 20chan** [comment]
이거 사실 어이없는건데 음

**Comment by 20chan** [comment]
@bigblueberry Grid GUI 처리 버그이기도 한데 내가 Grid를 수정해서 고치는게 괜찮겠지?

**Comment by yenapple** [comment]
Grid 였음>>? 그럼 그렇게 하자

**Comment by 20chan** [comment]
phillyai/Grid#2 문제 해결 완료, Grid 풀 후에 빌드하고 솔루션 정리 -> 다시 빌드하면 잘 될거야
